#!/bin/bash
# Regenerate watch/Sources/BuildInfo.swift with version + git rev + build time.
# GameView shows these as the on-screen beta "build tell" (DEBUG builds only),
# matching the Flutter app's tell so a specific watch build is identifiable.
# Run by the Xcode pre-build phase (see project.yml preBuildScripts).
set -euo pipefail

cd "$(dirname "$0")/.."                          # watch/
ver="${MARKETING_VERSION:-?}"
[ -n "${CURRENT_PROJECT_VERSION:-}" ] && ver="${ver}+${CURRENT_PROJECT_VERSION}"
rev=$(git rev-parse --short HEAD 2>/dev/null || echo '?')
git diff --quiet 2>/dev/null || rev="${rev}*"
ts=$(date -u +'%m-%d %H:%MZ')

cat > Sources/BuildInfo.swift <<EOF
// GENERATED by tool/stamp_watch.sh — do not edit by hand.
enum BuildInfo {
    static let version = "${ver}"
    static let rev = "${rev}"
    static let time = "${ts}"
    static var tell: String { "\(version) · \(rev) · \(time)" }
}
EOF
echo "stamped BuildInfo.swift: ${ver} ${rev} ${ts}"
