// GENERATED by tool/stamp_build.sh — do not edit by hand.
// Surfaced as the on-screen beta "build tell" (see _showBuildTell in main.dart).
const String kBuildVersion = '2.1.0+283';
const String kBuildRev = '639b0fc';
const String kBuildTime = '06-06 03:30Z';
