// GENERATED by tool/stamp_watch.sh — do not edit by hand.
enum BuildInfo {
    static let version = "2.1.0+283"
    static let rev = "639b0fc*"
    static let time = "06-06 03:32Z"
    static var tell: String { "\(version) · \(rev) · \(time)" }
}
