// GENERATED by tool/gen_skin_registry.sh — do not edit by hand.
//
// Public packs only. Device-derived packs are never named here: they live
// in the gitignored lib/skin/packs_private/ and are registered by the
// generated entry point in that directory, which this file cannot see.
// This file is tracked, so it must compile in a clone that has no such
// directory. See SKINS.md.

import 'registry.dart';
import 'packs/default_pack.dart' as pack_default;

/// Fills the pack table with the packs that ship unconditionally.
/// Called once from runMathieu() before anything reads the table.
void registerBuiltinSkins() {
  SkinRegistry.register('default', pack_default.buildSkin);
  SkinRegistry.debugAssertNothingSensitive();
}
