// Permutation arithmetic, in the engine's own convention.
//
// A permutation is a List<int> of length n where p[seat] is the piece value
// sitting at that seat — the same thing mathieu_get_arrangement fills in.
//
// Composition matches Toolbox's Permutation::operator*= exactly:
//
//     (a * b)[i] == a[b[i]]
//
// so `*` is ordinary function composition with the RIGHT factor applied first,
// and a move right-multiplies the state (`p *= R`). A word g1 g2 … gk played
// from position P therefore lands on P·g1·g2·…·gk.
//
// Nothing here imports Flutter: this is the layer the tests hammer.

import 'dart:math' as math;

/// Length of every permutation in this game. The engine's nBalls.
const int kBalls = 12;

List<int> identityPerm([int n = kBalls]) => List<int>.generate(n, (i) => i);

/// (a * b)[i] = a[b[i]].
List<int> compose(List<int> a, List<int> b) =>
    List<int>.generate(b.length, (i) => a[b[i]]);

List<int> inversePerm(List<int> a) {
  final r = List<int>.filled(a.length, 0);
  for (var i = 0; i < a.length; i++) {
    r[a[i]] = i;
  }
  return r;
}

bool isIdentityPerm(List<int> p) {
  for (var i = 0; i < p.length; i++) {
    if (p[i] != i) return false;
  }
  return true;
}

bool permEquals(List<int> a, List<int> b) {
  if (a.length != b.length) return false;
  for (var i = 0; i < a.length; i++) {
    if (a[i] != b[i]) return false;
  }
  return true;
}

/// Disjoint cycles, fixed points suppressed. Ported from Permutation::cycles.
List<List<int>> cyclesOf(List<int> p) {
  final seen = List<bool>.filled(p.length, false);
  final out = <List<int>>[];
  for (var i = 0; i < p.length; i++) {
    if (seen[i]) continue;
    final c = <int>[];
    var j = i;
    while (!seen[j]) {
      seen[j] = true;
      c.add(j);
      j = p[j];
    }
    if (c.length > 1) out.add(c);
  }
  return out;
}

/// Cycle lengths, longest first — e.g. [3, 3, 3] or [4, 4].
List<int> cycleType(List<int> p) {
  final t = cyclesOf(p).map((c) => c.length).toList()..sort((a, b) => b - a);
  return t;
}

/// The seats this element actually disturbs, ascending.
List<int> supportOf(List<int> p) {
  final s = <int>[];
  for (var i = 0; i < p.length; i++) {
    if (p[i] != i) s.add(i);
  }
  return s;
}

/// The seats it leaves alone, ascending.
List<int> fixedOf(List<int> p) {
  final s = <int>[];
  for (var i = 0; i < p.length; i++) {
    if (p[i] == i) s.add(i);
  }
  return s;
}

int _gcd(int a, int b) => b == 0 ? a : _gcd(b, a % b);

/// How many times you must repeat it to get back home: lcm of the cycle lengths.
int orderOf(List<int> p) {
  var o = 1;
  for (final c in cyclesOf(p)) {
    o = o ~/ _gcd(o, c.length) * c.length;
  }
  return o;
}

/// x · m · x⁻¹ — "do the setup, do the macro, undo the setup".
///
/// Its support is the image of m's support under x:
///   supp(x·m·x⁻¹) == { x[i] : i in supp(m) }
/// which is exactly what lets the app aim a macro at chosen seats.
List<int> conjugate(List<int> x, List<int> m) =>
    compose(compose(x, m), inversePerm(x));

/// Where conjugating by [x] sends [seats], as a sorted list.
List<int> imageOfSeats(List<int> x, Iterable<int> seats) {
  final out = seats.map((i) => x[i]).toList()..sort();
  return out;
}

/// [a, b] = a · b · a⁻¹ · b⁻¹.
List<int> commutator(List<int> a, List<int> b) =>
    compose(compose(compose(a, b), inversePerm(a)), inversePerm(b));

/// Cycle notation, e.g. "(0 6 3)(1 11 8)(4 10 7)". "(identity)" when empty.
String cyclesString(List<int> p) {
  final cs = cyclesOf(p);
  if (cs.isEmpty) return '(identity)';
  return cs.map((c) => '(${c.join(" ")})').join('');
}

/// Cycle type as "3+3+3", or "identity".
String cycleTypeString(List<int> p) {
  final t = cycleType(p);
  return t.isEmpty ? 'identity' : t.join('+');
}

/// A pseudo-random element of the group generated by the moves, used only where
/// an arbitrary element is wanted (tests, sampling). Not the engine's random().
List<int> randomWordPerm(math.Random rnd, List<int> r, List<int> s, int len) {
  var p = identityPerm(r.length);
  for (var i = 0; i < len; i++) {
    p = rnd.nextBool() ? compose(p, r) : compose(p, s);
  }
  return p;
}
