#!/bin/bash
# Regenerate the skin pack wiring from the pack files on disk.
#
# A pack is a file named <id>_pack.dart exposing `Skin buildSkin()`:
#   lib/skin/packs/          ships always (today: default_pack.dart only)
#   lib/skin/packs_private/  device-derived packs — GITIGNORED here; the source
#                            of truth is a wapex-only repo, and each pack is
#                            emitted behind its own compile-time flag.
#
# TWO OUTPUTS, and the split is the whole point:
#
#   lib/skin/registry_packs.g.dart              TRACKED. Public packs only.
#       Never names, imports or otherwise mentions a private pack, whether or
#       not packs_private/ happens to be on this disk. That is what lets it be
#       committed: a clone with no packs_private/ — which is every clone but
#       the one holding the private repo — still analyzes, tests and builds.
#
#   lib/skin/packs_private/main_private.dart    GITIGNORED (lives in the
#       ignored directory). An alternative Flutter entry point that imports the
#       private packs, registers the ones their flags enable, and hands off to
#       runMathieu() in lib/main.dart. Only written when packs_private/ exists.
#
# An earlier version emitted the private imports into registry_packs.g.dart
# itself. That file is tracked, so committing it from a machine that had the
# private packs broke every other clone with three "Target of URI doesn't
# exist" errors — and leaked the pack names into the public tree besides. Do
# not merge the two outputs back together.
#
# Droppable-pack workflow, no app-code edit either way:
#   drop packs_private/ in, re-run this, then build the private entry point
#     flutter build web -t lib/skin/packs_private/main_private.dart \
#                       --dart-define=SKIN_FLATPACK=true
#   delete packs_private/, re-run this, build normally, and the packs are gone.
#
# Run before any build; deploy.sh and tool/stamp_build.sh sit next to it.
set -euo pipefail

cd "$(dirname "$0")/.."                       # flutter/

pub_out=lib/skin/registry_packs.g.dart
priv_dir=lib/skin/packs_private
priv_out="$priv_dir/main_private.dart"

# snake_case pack id -> lowerCamelCase Dart identifier, so a multi-word id
# (transfer_ring) does not emit a constant_identifier_names lint.
camel() {
  echo "$1" | awk -F_ '{printf "%s", $1; for (i = 2; i <= NF; i++)
                        printf "%s%s", toupper(substr($i, 1, 1)), substr($i, 2)}'
}

flag_of() { echo "SKIN_$(echo "$1" | tr '[:lower:]' '[:upper:]')"; }

# --- public packs -> the tracked registry ------------------------------------

pub_ids=()
for f in lib/skin/packs/*_pack.dart; do
  [ -e "$f" ] || continue
  pub_ids+=("$(basename "$f" _pack.dart)")
done

# 'default' must be registered first and unconditionally.
order=()
for i in "${!pub_ids[@]}"; do
  [ "${pub_ids[$i]}" = "default" ] && order+=("$i")
done
for i in "${!pub_ids[@]}"; do
  [ "${pub_ids[$i]}" = "default" ] || order+=("$i")
done

{
  echo "// GENERATED by tool/gen_skin_registry.sh — do not edit by hand."
  echo "//"
  echo "// Public packs only. Device-derived packs are never named here: they live"
  echo "// in the gitignored lib/skin/packs_private/ and are registered by the"
  echo "// generated entry point in that directory, which this file cannot see."
  echo "// This file is tracked, so it must compile in a clone that has no such"
  echo "// directory. See SKINS.md."
  echo ""
  echo "import 'registry.dart';"
  for i in "${order[@]}"; do
    echo "import 'packs/${pub_ids[$i]}_pack.dart' as pack_${pub_ids[$i]};"
  done
  echo ""
  echo "/// Fills the pack table with the packs that ship unconditionally."
  echo "/// Called once from runMathieu() before anything reads the table."
  echo "void registerBuiltinSkins() {"
  for i in "${order[@]}"; do
    echo "  SkinRegistry.register('${pub_ids[$i]}', pack_${pub_ids[$i]}.buildSkin);"
  done
  echo "  SkinRegistry.debugAssertNothingSensitive();"
  echo "}"
} > "$pub_out.tmp"
mv "$pub_out.tmp" "$pub_out"
echo "generated $pub_out (${#pub_ids[@]} public pack(s): ${pub_ids[*]})"

# --- private packs -> the gitignored entry point ------------------------------

priv_ids=()
for f in "$priv_dir"/*_pack.dart; do
  [ -e "$f" ] || continue
  priv_ids+=("$(basename "$f" _pack.dart)")
done

if [ ${#priv_ids[@]} -eq 0 ]; then
  # No private packs on this machine. Remove any stale entry point so a later
  # build cannot pick up imports for packs that are no longer here.
  rm -f "$priv_out"
  echo "no private packs — $priv_out not written"
  exit 0
fi

{
  echo "// GENERATED by tool/gen_skin_registry.sh — do not edit by hand."
  echo "//"
  echo "// Alternative entry point for a build that carries device-derived packs."
  echo "// This file lives inside the gitignored packs_private/ directory and is"
  echo "// never committed; the tracked tree has no reference to it, which is why"
  echo "// a clone without packs_private/ still builds."
  echo "//"
  echo "//   flutter build web -t $priv_out --dart-define=$(flag_of "${priv_ids[0]}")=true"
  echo "//"
  echo "// Each pack is still behind its own const bool.fromEnvironment gate, so"
  echo "// even in this entry point an unflagged pack is tree-shaken out of the"
  echo "// binary rather than merely left unregistered."
  echo ""
  echo "import 'package:mathieu/main.dart';"
  echo "import 'package:mathieu/skin/registry.dart';"
  for id in "${priv_ids[@]}"; do
    echo "import '${id}_pack.dart' as pack_$id;"
  done
  echo ""
  for id in "${priv_ids[@]}"; do
    echo "const bool _$(camel "$id")Enabled = bool.fromEnvironment('$(flag_of "$id")');"
  done
  echo ""
  echo "void main() => runMathieu(registerExtraSkins: () {"
  for id in "${priv_ids[@]}"; do
    echo "      // hold until filing — see SKINS.md"
    echo "      // ignore: dead_code"
    echo "      if (_$(camel "$id")Enabled) {"
    echo "        SkinRegistry.register('$id', pack_$id.buildSkin);"
    echo "      }"
  done
  echo "    });"
} > "$priv_out.tmp"
mv "$priv_out.tmp" "$priv_out"
echo "generated $priv_out (${#priv_ids[@]} private pack(s): ${priv_ids[*]})"
