#!/bin/bash
# Regenerate flutter/lib/build_info.dart with the current version + git revision
# + build time. main.dart surfaces these as the on-screen "build tell" that is
# shown only in beta (non-release) builds, so a specific installed build can be
# identified at a glance.
#
# Run before any beta build. deploy.sh calls it automatically; the iOS Runner
# calls it from a pre-build "Stamp build_info" Run Script phase, so plain
# `flutter run` / Xcode builds re-stamp too.
set -euo pipefail

cd "$(dirname "$0")/.."                       # flutter/
ver=$(grep -E '^version:' pubspec.yaml | awk '{print $2}')
rev=$(git rev-parse --short HEAD 2>/dev/null || echo '?')
git diff --quiet 2>/dev/null || rev="${rev}*"   # trailing * => uncommitted tree
ts=$(date -u +'%m-%d %H:%MZ')

cat > lib/build_info.dart <<EOF
// GENERATED by tool/stamp_build.sh — do not edit by hand.
// Surfaced as the on-screen beta "build tell" (see _showBuildTell in main.dart).
const String kBuildVersion = '${ver}';
const String kBuildRev = '${rev}';
const String kBuildTime = '${ts}';
EOF
echo "stamped build_info.dart: ${ver} ${rev} ${ts}"
